version: "3.7"

services:
  svelte:
    image: node:16-alpine3.14
    volumes:
      - ./:/srv/app:rw,cached
    working_dir: /srv/app
    command: 'sh -c "npm install; npm run dev"'
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
      - target: 35729
        published: 35729
        protocol: tcp
